name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      TITLE: ${{ github.event.pull_request.title }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Student spotless
      if: startsWith(env.TITLE, '[Student]')
      run: ./gradlew dodam-student:spotlessCheck

    - name: Android Student Build with Gradle
      if: startsWith(env.TITLE, '[Student]')
      run: ./gradlew dodam-student:clean assembleRelease --parallel

    - name: Run Teacher spotless
      if: startsWith(env.TITLE, '[Teacher]')
      run: ./gradlew dodam-teacher-android:spotlessCheck
    
    - name: Android Teacher Build with Gradle
      if: startsWith(env.TITLE, '[Teacher]')
      run: ./gradlew dodam-teacher-android:clean assembleRelease --parallel

    - name: Android Core Build with Gradle
      if: startsWith(env.TITLE, '[Core]')
      run: ./gradlew spotlessCheck
    
    - name: Android Core Build with Gradle
      if: startsWith(env.TITLE, '[Core]')
      run: |
        ./gradlew dodam-teacher-android:clean assembleRelease --parallel
        ./gradlew dodam-student:assembleRelease --parallel


    
